### ISSUE TITLE
 reduce report file?

### ISSUE THREAD

**Issue by Anton19780301** [xFreed0m/RDPassSpray#3]
Good afternoon.
When I spray, a large report file is formed (I have more than 500k users). Is it possible to write only a successful input to an SCV file?

**Comment by Anton19780301** [comment]
Thank you, of course you are right. But 500k is 500k. After 3 passwords, I get a list of more than 1,048,576 lines, and the office does not open it completely.
Of course, i can run the spray with only one password, but want to leave the spray to work for a week and do other work. That would be just a nice feature.
But if not, then no.
By the way - a good tool. I already found 15k passwords from the dictionary and started an internal investigation, the boss will be pleased.

**Comment by xFreed0m** [comment]
i'm happy to hear you like it!
i've added your request to the feature list, might be able to corporate it for the next commit. will keep this thread posted

**Comment by xFreed0m** [comment]
Hi @Anton19780301 , I've added the feature you requested but i don't have an environment to test it.
If you wish to test it out, it's under the dev branch.

let me know!

**Comment by Anton19780301** [comment]
I get error, It strange

root@l:~/RDPassSpray-dev# python3 RDPassSpray.py -U all.txt -P Pass.txt -d MYREGIONSDOMEN -t 10.151.0.6
Traceback (most recent call last):
  File "RDPassSpray.py", line 387, in <module>
    main()
  File "RDPassSpray.py", line 325, in main
    args = args_parse()
  File "RDPassSpray.py", line 34, in args_parse
    required=True)
  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1584, in _add_action
    raise ValueError(msg)
ValueError: mutually exclusive arguments must be optional

**Comment by xFreed0m** [comment]
please download the dev branch again and try again please, should be fixed.

**Comment by Anton19780301** [comment]
Good afternoon.
I'm testing for about a day.
Very grateful - the report file has greatly decreased in size. This makes me happy.

**Comment by xFreed0m** [comment]
i'm gald to hear that! i'm waiting for an update that all is working as expected so i could merge the dev brance into master.

thanks!
