### ISSUE TITLE
Doesnt ouput target

### ISSUE THREAD

**Issue by Sir-FIS** [xFreed0m/RDPassSpray#8]
Hey mate, real quick when I run the tool in my lab it says "Cred successful (maybe even Admin access!): USER :: PASS " but it doesnt tell me what machines it is. I added a basic 

`+ '@'  + target ` to each code print statement to make it easier for myself when using it. 

I just think its a really good tool and something simple like the above would be a real QoL improvement

**Comment by xFreed0m** [comment]
sounds good! will you open a PR with your changes?

**Comment by Sir-FIS** [comment]
sure i'll create a branch called "add_target", put me down as a collaborator

**Comment by Sir-FIS** [comment]
ignore the above @xFreed0m , I worked out how to use forks
